/// NbaActionsWidget — displays ranked Next Best Actions generated by the hook engine.
///
/// Plugs into any screen that shows captured content (notes, scans, insights)
/// and provides an always-on "What should I do next?" section.
library;

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:fikr/controllers/app_controller.dart';
import '../controllers/subscription_controller.dart';
import '../models/action_card.dart';
import '../models/app_config.dart';
import '../services/storage_service.dart';
import '../tools/hooks/hook_engine.dart';
import '../tools/tool_interface.dart';
import 'action_preview_sheet.dart';

// ---------------------------------------------------------------------------
// Public widget
// ---------------------------------------------------------------------------

/// Displays ranked Next Best Actions for a given [NbaContext].
class NbaActionsWidget extends StatefulWidget {
  /// The context to evaluate hooks against.
  final NbaContext context;

  /// Which trigger fired this evaluation.
  final HookTrigger? trigger;

  /// Maximum number of actions to display.
  final int maxActions;

  /// Minimum score threshold for actions.
  final double minScore;

  /// Hook names to exclude from evaluation.
  final List<String>? excludedHooks;

  /// Callback for local actions (custom type, no URL).
  final void Function(ActionCard action, String hookName)? onLocalAction;

  /// Whether to show the section header.
  final bool showHeader;

  /// Custom header text.
  final String? headerText;

  /// Whether to expand the actions list by default.
  final bool initiallyExpanded;

  const NbaActionsWidget({
    super.key,
    required this.context,
    this.trigger,
    this.maxActions = 10,
    this.minScore = 0.3,
    this.excludedHooks,
    this.onLocalAction,
    this.showHeader = true,
    this.headerText,
    this.initiallyExpanded = false,
  });

  @override
  State<NbaActionsWidget> createState() => _NbaActionsWidgetState();
}

class _NbaActionsWidgetState extends State<NbaActionsWidget>
    with SingleTickerProviderStateMixin {
  late final AnimationController _fadeController;
  late final Animation<double> _fadeAnimation;

  List<RankedAction> _actions = [];
  bool _loading = true;
  bool _expanded = false;
  String? _error;

  @override
  void initState() {
    super.initState();
    _expanded = widget.initiallyExpanded;
    _fadeController = AnimationController(
      duration: const Duration(milliseconds: 400),
      vsync: this,
    );
    _fadeAnimation = CurvedAnimation(
      parent: _fadeController,
      curve: Curves.easeInOut,
    );
    _evaluate();
  }

  @override
  void didUpdateWidget(covariant NbaActionsWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.context != widget.context) {
      _evaluate();
    }
  }

  @override
  void dispose() {
    _fadeController.dispose();
    super.dispose();
  }

  Future<void> _evaluate() async {
    setState(() {
      _loading = true;
      _actions = [];
      _error = null;
      _expanded = widget.initiallyExpanded;
    });

    try {
      final registry = ActionHookRegistry.instance;
      final tier = _resolveTier();

      // Always inject a ToolContext so hooks can access config, storage, and
      // the user's API key — even when the widget caller did not provide one.
      final ctx = _injectToolContext(widget.context, tier);

      _actions = await registry.run(
        ctx,
        minScore: widget.minScore,
        maxActions: widget.maxActions,
        excludedHooks: widget.excludedHooks,
        tier: tier,
      );
    } catch (e) {
      _error = e.toString();
    }

    if (mounted) {
      setState(() {
        _loading = false;
      });
      _fadeController.forward(from: 0.0);
    }
  }

  ToolTier _resolveTier() {
    try {
      final sub = Get.find<SubscriptionController>();
      if (sub.isPro) return ToolTier.pro;
      if (sub.isPlus) return ToolTier.plus;
    } catch (_) {}
    return ToolTier.free;
  }

  /// Builds a [ToolContext] from GetX-registered services and merges it into
  /// the provided [NbaContext]. If the caller already supplied a toolContext,
  /// it is kept as-is.
  NbaContext _injectToolContext(NbaContext ctx, ToolTier tier) {
    if (ctx.toolContext != null) return ctx; // already set by caller

    AppConfig config;
    StorageService? storage;

    try {
      final appCtrl = Get.find<AppController>();
      config = appCtrl.config.value;
      storage = appCtrl.storage;
    } catch (_) {
      config = AppConfig.fromJson({});
    }

    final toolCtx = ToolContext(
      planTier: tier,
      config: config,
      storage: storage,
    );

    return NbaContext(
      source: ctx.source,
      text: ctx.text,
      analysis: ctx.analysis,
      scan: ctx.scan,
      note: ctx.note,
      existingActions: ctx.existingActions,
      toolContext: toolCtx,
      trigger: ctx.trigger,
      metadata: ctx.metadata,
    );
  }

  @override
  Widget build(BuildContext context) {
    final effectiveActions = _loading ? [] : _actions;

    if (effectiveActions.isEmpty && !_loading && _error == null) {
      return const SizedBox.shrink();
    }

    if (_error != null && !_loading) {
      return _ErrorState(error: _error!);
    }

    return FadeTransition(
      opacity: _fadeAnimation,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (widget.showHeader) ...[
            _Header(
              title: widget.headerText ?? 'Next Best Actions',
              count: effectiveActions.length,
              isExpanded: _expanded,
              loading: _loading,
              onToggle: () {
                setState(() {
                  _expanded = !_expanded;
                });
              },
            ),
            const SizedBox(height: 12),
          ],
          if (_loading)
            _LoadingSkeleton()
          else
            ...(_expanded || widget.initiallyExpanded
                    ? effectiveActions
                    : effectiveActions.take(3))
                .map(
                  (action) => ActionCardWidget(
                    action: action.action,
                    hookName: action.hookName,
                    urgency: action.urgency,
                    compact: !_expanded && !widget.initiallyExpanded,
                    onLocalAction: widget.onLocalAction,
                  ),
                ),
          if (!_loading &&
              effectiveActions.length > 3 &&
              !widget.initiallyExpanded)
            Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Center(
                child: TextButton.icon(
                  onPressed: () {
                    setState(() {
                      _expanded = !_expanded;
                    });
                  },
                  icon: Icon(
                    _expanded ? Icons.arrow_upward : Icons.arrow_downward,
                    size: 16,
                  ),
                  label: Text(
                    _expanded
                        ? 'Show less'
                        : 'Show all ${effectiveActions.length} actions',
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

class _Header extends StatelessWidget {
  final String title;
  final int count;
  final bool isExpanded;
  final bool loading;
  final VoidCallback onToggle;

  const _Header({
    required this.title,
    required this.count,
    required this.isExpanded,
    required this.loading,
    required this.onToggle,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return InkWell(
      onTap: onToggle,
      borderRadius: BorderRadius.circular(12),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 4),
        child: Row(
          children: [
            Icon(Icons.flash_on, size: 20, color: colorScheme.primary),
            const SizedBox(width: 8),
            Text(
              title,
              style: theme.textTheme.titleSmall?.copyWith(
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(width: 8),
            if (loading)
              const SizedBox(
                width: 16,
                height: 16,
                child: CircularProgressIndicator(strokeWidth: 2),
              )
            else
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: BoxDecoration(
                  color: colorScheme.primaryContainer,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  '$count',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: colorScheme.onPrimaryContainer,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            const Spacer(),
            Icon(
              isExpanded ? Icons.arrow_upward : Icons.arrow_downward,
              size: 16,
              color: colorScheme.onSurface.withValues(alpha: 0.4),
            ),
          ],
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Loading Skeleton
// ---------------------------------------------------------------------------

class _LoadingSkeleton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final bgColor = colorScheme.surfaceContainerHighest.withValues(alpha: 0.3);

    return Column(
      children: List.generate(
        3,
        (i) => Padding(
          padding: const EdgeInsets.only(bottom: 10),
          child: Container(
            height: 72,
            decoration: BoxDecoration(
              color: bgColor,
              borderRadius: BorderRadius.circular(16),
            ),
          ),
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Error State
// ---------------------------------------------------------------------------

class _ErrorState extends StatelessWidget {
  final String error;

  const _ErrorState({required this.error});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: colorScheme.errorContainer.withValues(alpha: 0.3),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          Icon(Icons.error_outline, color: colorScheme.error, size: 18),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              'Actions unavailable',
              style: theme.textTheme.bodySmall?.copyWith(
                color: colorScheme.onErrorContainer,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Action Card
// ---------------------------------------------------------------------------

class ActionCardWidget extends StatelessWidget {
  final ActionCard action;
  final String? hookName;
  final ActionUrgency? urgency;
  final bool compact;
  final void Function(ActionCard action, String hookName)? onLocalAction;

  const ActionCardWidget({
    super.key,
    required this.action,
    this.hookName,
    this.urgency,
    this.compact = false,
    this.onLocalAction,
  });

  Color _getUrgencyColor(ColorScheme colorScheme) {
    switch (urgency ?? ActionUrgency.soon) {
      case ActionUrgency.now:
        return colorScheme.error;
      case ActionUrgency.soon:
        return Colors.orange;
      case ActionUrgency.later:
        return colorScheme.primary;
      case ActionUrgency.background:
        return colorScheme.surfaceContainerHighest;
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final hasUrl = action.url != null && action.url!.isNotEmpty;
    final urgencyColor = _getUrgencyColor(colorScheme);

    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: BorderSide(color: colorScheme.outline.withValues(alpha: 0.15)),
      ),
      child: InkWell(
        onTap: () => _handleAction(context),
        borderRadius: BorderRadius.circular(16),
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Row(
            crossAxisAlignment: compact
                ? CrossAxisAlignment.center
                : CrossAxisAlignment.start,
            children: [
              // Urgency indicator
              Container(
                width: 8,
                height: 8,
                decoration: BoxDecoration(
                  color: urgencyColor,
                  shape: BoxShape.circle,
                ),
              ),
              const SizedBox(width: 12),

              // Content
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      action.title,
                      style: theme.textTheme.titleSmall?.copyWith(
                        fontWeight: FontWeight.w600,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                    if (!compact && action.subtitle.isNotEmpty) ...[
                      const SizedBox(height: 4),
                      Text(
                        action.subtitle,
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: colorScheme.onSurface.withValues(alpha: 0.55),
                        ),
                        maxLines: 2,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                    const SizedBox(height: 8),
                    if (hookName != null)
                      Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 6,
                              vertical: 2,
                            ),
                            decoration: BoxDecoration(
                              color: colorScheme.secondaryContainer.withValues(
                                alpha: 0.4,
                              ),
                              borderRadius: BorderRadius.circular(6),
                            ),
                            child: Text(
                              hookName!,
                              style: theme.textTheme.labelSmall?.copyWith(
                                color: colorScheme.onSecondaryContainer,
                              ),
                            ),
                          ),
                        ],
                      ),
                  ],
                ),
              ),

              if (hasUrl && !compact) ...[
                const SizedBox(width: 12),
                FilledButton.tonal(
                  onPressed: () => _handleAction(context),
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 16,
                      vertical: 8,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Text(
                    action.ctaLabel,
                    style: theme.textTheme.labelMedium,
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  void _handleAction(BuildContext context) {
    if (action.isToolAction) {
      Get.bottomSheet(
        ActionPreviewSheet(action: action),
        isScrollControlled: true,
        backgroundColor: Colors.transparent,
      );
    } else if (action.url != null && action.url!.isNotEmpty) {
      _launchUrl(action.url!);
    } else {
      onLocalAction?.call(action, hookName ?? '');
    }
  }

  Future<void> _launchUrl(String url) async {
    final uri = Uri.tryParse(url);
    if (uri == null) return;

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.platformDefault);
    }
  }
}

// ---------------------------------------------------------------------------
// Stateless convenience widget
// ---------------------------------------------------------------------------

/// Stateless one-shot widget that evaluates hooks once and displays the result.
class NbaActionsBuilder extends StatelessWidget {
  final NbaContext context;
  final HookTrigger? trigger;
  final int maxActions;
  final double minScore;
  final List<String>? excludedHooks;
  final void Function(ActionCard action, String hookName)? onLocalAction;
  final Widget Function(BuildContext, AsyncSnapshot<List<RankedAction>>)
  builder;

  const NbaActionsBuilder({
    super.key,
    required this.context,
    this.trigger,
    this.maxActions = 10,
    this.minScore = 0.3,
    this.excludedHooks,
    this.onLocalAction,
    required this.builder,
  });

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<List<RankedAction>>(
      future: _evaluate(),
      builder: builder,
    );
  }

  Future<List<RankedAction>> _evaluate() async {
    try {
      final registry = ActionHookRegistry.instance;
      ToolTier tier = ToolTier.free;
      try {
        final sub = Get.find<SubscriptionController>();
        if (sub.isPro) {
          tier = ToolTier.pro;
        } else if (sub.isPlus) {
          tier = ToolTier.plus;
        }
      } catch (_) {}

      // Inject ToolContext if missing
      NbaContext ctx = context;
      if (ctx.toolContext == null) {
        AppConfig config;
        StorageService? storage;
        try {
          final appCtrl = Get.find<AppController>();
          config = appCtrl.config.value;
          storage = appCtrl.storage;
        } catch (_) {
          config = AppConfig.fromJson({});
        }
        ctx = NbaContext(
          source: ctx.source,
          text: ctx.text,
          analysis: ctx.analysis,
          scan: ctx.scan,
          note: ctx.note,
          existingActions: ctx.existingActions,
          toolContext: ToolContext(
            planTier: tier,
            config: config,
            storage: storage,
          ),
          trigger: ctx.trigger,
          metadata: ctx.metadata,
        );
      }

      return await registry.run(
        ctx,
        minScore: minScore,
        maxActions: maxActions,
        excludedHooks: excludedHooks,
        tier: tier,
      );
    } catch (_) {
      return [];
    }
  }
}
